language: ruby
rvm:
  - 1.8
  - 1.9
  - rbx-18mode
  - rbx-19mode
  - ree

before-install: wget http://download.guardtime.com/libgt-0.3.11-src.tgz  -O - | tar xfz - && cd libgt-0.3.11 && ./configure --disable-shared && make && sudo make install && cd ..

script: "ruby test/tc_guardtime.rb"
