language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
  - ree

install: 'wget http://download.guardtime.com/libgt-0.3.11-src.tgz  -O - | tar xfz - && cd libgt-0.3.11 &&  ./configure --silent --prefix=/usr && make && sudo make install && cd ..'

script: 
  - 'ruby ext/extconf.rb'
  - make
  - 'ruby test/tc_guardtime.rb'
  - 'gem build guardtime.gemspec'
